# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import steg_service_pb2 as steg__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x06\x63onfig\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12steg_service.proto\"&\n\x13GetWorkflowResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"%\n\x12SetWorkflowRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"&\n\x13SetWorkflowResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x13GetServicesResponse\x12/\n\x08services\x18\x01 \x03(\x0b\x32\x1d.steg_service.StegServiceInfo2\xe7\x01\n\rConfigService\x12\x46\n\x0fGetWorkflowFile\x12\x16.google.protobuf.Empty\x1a\x1b.config.GetWorkflowResponse\x12J\n\x0fSetWorkflowFile\x12\x1a.config.SetWorkflowRequest\x1a\x1b.config.SetWorkflowResponse\x12\x42\n\x0bGetServices\x12\x16.google.protobuf.Empty\x1a\x1b.config.GetServicesResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_GETWORKFLOWRESPONSE']._serialized_start=73
  _globals['_GETWORKFLOWRESPONSE']._serialized_end=111
  _globals['_SETWORKFLOWREQUEST']._serialized_start=113
  _globals['_SETWORKFLOWREQUEST']._serialized_end=150
  _globals['_SETWORKFLOWRESPONSE']._serialized_start=152
  _globals['_SETWORKFLOWRESPONSE']._serialized_end=190
  _globals['_GETSERVICESRESPONSE']._serialized_start=192
  _globals['_GETSERVICESRESPONSE']._serialized_end=262
  _globals['_CONFIGSERVICE']._serialized_start=265
  _globals['_CONFIGSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
