// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: steg_analysis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StegAnalysisService_Execute_FullMethodName = "/steg_analysis.StegAnalysisService/Execute"
)

// StegAnalysisServiceClient is the client API for StegAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StegAnalysisServiceClient interface {
	Execute(ctx context.Context, in *StegAnalysisRequest, opts ...grpc.CallOption) (*StegAnalysisResponse, error)
}

type stegAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStegAnalysisServiceClient(cc grpc.ClientConnInterface) StegAnalysisServiceClient {
	return &stegAnalysisServiceClient{cc}
}

func (c *stegAnalysisServiceClient) Execute(ctx context.Context, in *StegAnalysisRequest, opts ...grpc.CallOption) (*StegAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StegAnalysisResponse)
	err := c.cc.Invoke(ctx, StegAnalysisService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StegAnalysisServiceServer is the server API for StegAnalysisService service.
// All implementations must embed UnimplementedStegAnalysisServiceServer
// for forward compatibility.
type StegAnalysisServiceServer interface {
	Execute(context.Context, *StegAnalysisRequest) (*StegAnalysisResponse, error)
	mustEmbedUnimplementedStegAnalysisServiceServer()
}

// UnimplementedStegAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStegAnalysisServiceServer struct{}

func (UnimplementedStegAnalysisServiceServer) Execute(context.Context, *StegAnalysisRequest) (*StegAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedStegAnalysisServiceServer) mustEmbedUnimplementedStegAnalysisServiceServer() {}
func (UnimplementedStegAnalysisServiceServer) testEmbeddedByValue()                             {}

// UnsafeStegAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StegAnalysisServiceServer will
// result in compilation errors.
type UnsafeStegAnalysisServiceServer interface {
	mustEmbedUnimplementedStegAnalysisServiceServer()
}

func RegisterStegAnalysisServiceServer(s grpc.ServiceRegistrar, srv StegAnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedStegAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StegAnalysisService_ServiceDesc, srv)
}

func _StegAnalysisService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StegAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegAnalysisServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegAnalysisService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegAnalysisServiceServer).Execute(ctx, req.(*StegAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StegAnalysisService_ServiceDesc is the grpc.ServiceDesc for StegAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StegAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steg_analysis.StegAnalysisService",
	HandlerType: (*StegAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _StegAnalysisService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steg_analysis.proto",
}
