// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: steg_services.proto
#ifndef GRPC_steg_5fservices_2eproto__INCLUDED
#define GRPC_steg_5fservices_2eproto__INCLUDED

#include "steg_services.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace steg_services {

class StegService final {
 public:
  static constexpr char const* service_full_name() {
    return "steg_services.StegService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::steg_services::StegServiceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>> AsyncExecute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>>(AsyncExecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>> PrepareAsyncExecute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>>(PrepareAsyncExecuteRaw(context, request, cq));
    }
    virtual ::grpc::Status GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceReturnFields* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>> AsyncGetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>>(AsyncGetReturnFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>> PrepareAsyncGetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>>(PrepareAsyncGetReturnFieldsRaw(context, request, cq));
    }
    virtual ::grpc::Status GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceAvailableParameter* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>> AsyncGetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>>(AsyncGetReturnAvailableParameterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>> PrepareAsyncGetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>>(PrepareAsyncGetReturnAvailableParameterRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>* AsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceResponse>* PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>* AsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceReturnFields>* PrepareAsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>* AsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::steg_services::StegServiceAvailableParameter>* PrepareAsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::steg_services::StegServiceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>> AsyncExecute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>>(AsyncExecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>> PrepareAsyncExecute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>>(PrepareAsyncExecuteRaw(context, request, cq));
    }
    ::grpc::Status GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceReturnFields* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>> AsyncGetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>>(AsyncGetReturnFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>> PrepareAsyncGetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>>(PrepareAsyncGetReturnFieldsRaw(context, request, cq));
    }
    ::grpc::Status GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceAvailableParameter* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>> AsyncGetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>>(AsyncGetReturnAvailableParameterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>> PrepareAsyncGetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>>(PrepareAsyncGetReturnAvailableParameterRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, std::function<void(::grpc::Status)>) override;
      void Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, std::function<void(::grpc::Status)>) override;
      void GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, std::function<void(::grpc::Status)>) override;
      void GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>* AsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>* PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>* AsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>* PrepareAsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>* AsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>* PrepareAsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Execute_;
    const ::grpc::internal::RpcMethod rpcmethod_GetReturnFields_;
    const ::grpc::internal::RpcMethod rpcmethod_GetReturnAvailableParameter_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Execute(::grpc::ServerContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response);
    virtual ::grpc::Status GetReturnFields(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response);
    virtual ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Execute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecute(::grpc::ServerContext* context, ::steg_services::StegServiceRequest* request, ::grpc::ServerAsyncResponseWriter< ::steg_services::StegServiceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReturnFields(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::steg_services::StegServiceReturnFields>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReturnAvailableParameter(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::steg_services::StegServiceAvailableParameter>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Execute<WithAsyncMethod_GetReturnFields<WithAsyncMethod_GetReturnAvailableParameter<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Execute() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response) { return this->Execute(context, request, response); }));}
    void SetMessageAllocatorFor_Execute(
        ::grpc::MessageAllocator< ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Execute(
      ::grpc::CallbackServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response) { return this->GetReturnFields(context, request, response); }));}
    void SetMessageAllocatorFor_GetReturnFields(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReturnFields(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response) { return this->GetReturnAvailableParameter(context, request, response); }));}
    void SetMessageAllocatorFor_GetReturnAvailableParameter(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReturnAvailableParameter(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Execute<WithCallbackMethod_GetReturnFields<WithCallbackMethod_GetReturnAvailableParameter<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Execute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Execute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReturnFields(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReturnAvailableParameter(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Execute() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Execute(context, request, response); }));
    }
    ~WithRawCallbackMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Execute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReturnFields(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReturnFields(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReturnAvailableParameter(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReturnAvailableParameter(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Execute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse>* streamer) {
                       return this->StreamedExecute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Execute(::grpc::ServerContext* /*context*/, const ::steg_services::StegServiceRequest* /*request*/, ::steg_services::StegServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::steg_services::StegServiceRequest,::steg_services::StegServiceResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReturnFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReturnFields() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields>* streamer) {
                       return this->StreamedGetReturnFields(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReturnFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReturnFields(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceReturnFields* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReturnFields(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::steg_services::StegServiceReturnFields>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReturnAvailableParameter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReturnAvailableParameter() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter>* streamer) {
                       return this->StreamedGetReturnAvailableParameter(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReturnAvailableParameter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReturnAvailableParameter(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::steg_services::StegServiceAvailableParameter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReturnAvailableParameter(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::steg_services::StegServiceAvailableParameter>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Execute<WithStreamedUnaryMethod_GetReturnFields<WithStreamedUnaryMethod_GetReturnAvailableParameter<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Execute<WithStreamedUnaryMethod_GetReturnFields<WithStreamedUnaryMethod_GetReturnAvailableParameter<Service > > > StreamedService;
};

}  // namespace steg_services


#endif  // GRPC_steg_5fservices_2eproto__INCLUDED
