// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: steg_services.proto

#include "steg_services.pb.h"
#include "steg_services.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace steg_services {

static const char* StegService_method_names[] = {
  "/steg_services.StegService/Execute",
  "/steg_services.StegService/GetReturnFields",
  "/steg_services.StegService/GetReturnAvailableParameter",
};

std::unique_ptr< StegService::Stub> StegService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StegService::Stub> stub(new StegService::Stub(channel, options));
  return stub;
}

StegService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Execute_(StegService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReturnFields_(StegService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReturnAvailableParameter_(StegService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StegService::Stub::Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::steg_services::StegServiceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Execute_, context, request, response);
}

void StegService::Stub::async::Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, std::move(f));
}

void StegService::Stub::async::Execute(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>* StegService::Stub::PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::steg_services::StegServiceResponse, ::steg_services::StegServiceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Execute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceResponse>* StegService::Stub::AsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_services::StegServiceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StegService::Stub::GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceReturnFields* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReturnFields_, context, request, response);
}

void StegService::Stub::async::GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReturnFields_, context, request, response, std::move(f));
}

void StegService::Stub::async::GetReturnFields(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReturnFields_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>* StegService::Stub::PrepareAsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::steg_services::StegServiceReturnFields, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReturnFields_, context, request);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceReturnFields>* StegService::Stub::AsyncGetReturnFieldsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReturnFieldsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StegService::Stub::GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::steg_services::StegServiceAvailableParameter* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReturnAvailableParameter_, context, request, response);
}

void StegService::Stub::async::GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReturnAvailableParameter_, context, request, response, std::move(f));
}

void StegService::Stub::async::GetReturnAvailableParameter(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReturnAvailableParameter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>* StegService::Stub::PrepareAsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::steg_services::StegServiceAvailableParameter, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReturnAvailableParameter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::steg_services::StegServiceAvailableParameter>* StegService::Stub::AsyncGetReturnAvailableParameterRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReturnAvailableParameterRaw(context, request, cq);
  result->StartCall();
  return result;
}

StegService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StegService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StegService::Service, ::steg_services::StegServiceRequest, ::steg_services::StegServiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StegService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::steg_services::StegServiceRequest* req,
             ::steg_services::StegServiceResponse* resp) {
               return service->Execute(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StegService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StegService::Service, ::google::protobuf::Empty, ::steg_services::StegServiceReturnFields, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StegService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::steg_services::StegServiceReturnFields* resp) {
               return service->GetReturnFields(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StegService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StegService::Service, ::google::protobuf::Empty, ::steg_services::StegServiceAvailableParameter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StegService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::steg_services::StegServiceAvailableParameter* resp) {
               return service->GetReturnAvailableParameter(ctx, req, resp);
             }, this)));
}

StegService::Service::~Service() {
}

::grpc::Status StegService::Service::Execute(::grpc::ServerContext* context, const ::steg_services::StegServiceRequest* request, ::steg_services::StegServiceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StegService::Service::GetReturnFields(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceReturnFields* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StegService::Service::GetReturnAvailableParameter(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::steg_services::StegServiceAvailableParameter* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace steg_services

