// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: steg_analysis.proto

#include "steg_analysis.pb.h"
#include "steg_analysis.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace steg_analysis {

static const char* StegAnalysisService_method_names[] = {
  "/steg_analysis.StegAnalysisService/Execute",
};

std::unique_ptr< StegAnalysisService::Stub> StegAnalysisService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StegAnalysisService::Stub> stub(new StegAnalysisService::Stub(channel, options));
  return stub;
}

StegAnalysisService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Execute_(StegAnalysisService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StegAnalysisService::Stub::Execute(::grpc::ClientContext* context, const ::steg_analysis::StegAnalysisRequest& request, ::steg_analysis::StegAnalysisResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::steg_analysis::StegAnalysisRequest, ::steg_analysis::StegAnalysisResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Execute_, context, request, response);
}

void StegAnalysisService::Stub::async::Execute(::grpc::ClientContext* context, const ::steg_analysis::StegAnalysisRequest* request, ::steg_analysis::StegAnalysisResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::steg_analysis::StegAnalysisRequest, ::steg_analysis::StegAnalysisResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, std::move(f));
}

void StegAnalysisService::Stub::async::Execute(::grpc::ClientContext* context, const ::steg_analysis::StegAnalysisRequest* request, ::steg_analysis::StegAnalysisResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::steg_analysis::StegAnalysisResponse>* StegAnalysisService::Stub::PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_analysis::StegAnalysisRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::steg_analysis::StegAnalysisResponse, ::steg_analysis::StegAnalysisRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Execute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::steg_analysis::StegAnalysisResponse>* StegAnalysisService::Stub::AsyncExecuteRaw(::grpc::ClientContext* context, const ::steg_analysis::StegAnalysisRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

StegAnalysisService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StegAnalysisService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StegAnalysisService::Service, ::steg_analysis::StegAnalysisRequest, ::steg_analysis::StegAnalysisResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StegAnalysisService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::steg_analysis::StegAnalysisRequest* req,
             ::steg_analysis::StegAnalysisResponse* resp) {
               return service->Execute(ctx, req, resp);
             }, this)));
}

StegAnalysisService::Service::~Service() {
}

::grpc::Status StegAnalysisService::Service::Execute(::grpc::ServerContext* context, const ::steg_analysis::StegAnalysisRequest* request, ::steg_analysis::StegAnalysisResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace steg_analysis

